Small cleanings and polishings
Cronenbrogues/cronenbroguelike pull request #89
Opened 2021-01-19 03:12 UTC by flosincapite

2021-01-19 17:18 UTC, xmunoz commented
Since this PR is growing much larger than expected. It would be helpful if you could summarize the changes in the PR description, so I know what to expect and test for in the next round of reviews.

2021-01-19 17:25 UTC, xmunoz requested changes
I also don't understand why `modify` was re-named to `heal_or_harm`. My general review is that it's hard to understand what's going on in this PR, likely because of poor naming choices.

2021-01-19 17:25 UTC, xmunoz commented on engine/actor.py
> +        Insanity(100),
Does this mean that the initial value of insanity is 100? If so, why?

2021-01-19 17:25 UTC, xmunoz commented on engine/say.py
> +        insanity = G.player.insanity.current_value
The distinction between `value` and `current_value` isn't clear to me. Could you choose different variable names that elucidate the difference between these values?

2021-01-20 23:23 UTC, flosincapite commented
I will break this up into some smaller PRs.

2021-01-21 02:24 UTC, flosincapite commented
This change is now subsumed by changes #88 , #90 , #91 , and #92 , q.v.

2021-01-21 02:24 UTC, closed without merging